# Generated by Django 5.1.1 on 2024-09-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bidder_name', models.CharField(max_length=255)),
                ('bidder_link', models.URLField()),
                ('publication_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('cpv_code', models.CharField(max_length=100)),
            ],
        ),
    ]
