# Generated by Django 5.1.1 on 2024-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='announcement_type',
            field=models.CharField(default='Visos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='purchase_type',
            field=models.CharField(default='Visos', max_length=100),
            preserve_default=False,
        ),
    ]
